apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: burger-order-np
  name: burger-order-np
spec:
  ports:
    - name: 8000-8000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: burger-order
  type: ClusterIP
