apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: authserver
  name: authserver
spec:
  ports:
    - name: 8000-8000
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: authserver
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: authserver-np
  name: authserver-np
spec:
  ports:
    - name: 8000-8000
      nodePort: 32348
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: authserver
  type: NodePort